# Generated by Django 4.2.24 on 2025-09-08 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spins_total', models.PositiveIntegerField(default=0)),
                ('spins_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('available_to', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='cases.case')),
            ],
            options={
                'verbose_name': 'Приз кейса',
                'verbose_name_plural': 'Призы кейса',
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_limited', models.BooleanField(default=False)),
                ('is_timed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип кейса',
                'verbose_name_plural': 'Типы кейсов',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.caseprize')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Крутка',
                'verbose_name_plural': 'Крутки',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casetype'),
        ),
    ]
