# Generated by Django 4.2.24 on 2025-09-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spin',
            name='client_seed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='spin',
            name='nonce',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='spin',
            name='rng_value',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='spin',
            name='roll_digest',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='spin',
            name='server_seed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spin',
            name='server_seed_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='spin',
            name='weights_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
