# Generated by Django 4.2.24 on 2025-09-25 05:05

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_spin_client_seed_spin_nonce_spin_rng_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=cases.models.upload_to_case, verbose_name='Аватар кейса'),
        ),
    ]
