# Generated by Django 4.2.24 on 2025-09-25 08:17

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=cases.models.upload_to_case, verbose_name='Аватар кейса'),
        ),
    ]
