# Generated by Django 4.2.24 on 2025-10-13 17:17

import cases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название приза')),
                ('image', models.ImageField(blank=True, null=True, upload_to=cases.models.upload_to_prize, verbose_name='Изображение приза')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Приз',
                'verbose_name_plural': 'Призы',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='caseprize',
            name='amount_max_usd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=14, verbose_name='Максимальная сумма (USD)'),
        ),
        migrations.AddField(
            model_name='caseprize',
            name='amount_min_usd',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=14, verbose_name='Минимальная сумма (USD)'),
        ),
        migrations.AddField(
            model_name='spin',
            name='actual_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=14, verbose_name='Фактическая сумма выигрыша'),
        ),
        migrations.AddField(
            model_name='spin',
            name='case_prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.caseprize', verbose_name='Приз кейса'),
        ),
        migrations.AlterField(
            model_name='caseprize',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='caseprize',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caseprize',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес (вероятность)'),
        ),
        migrations.AlterField(
            model_name='spin',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_spins', to='cases.caseprize'),
        ),
        migrations.AddField(
            model_name='caseprize',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.prize', verbose_name='Приз'),
        ),
        migrations.AlterUniqueTogether(
            name='caseprize',
            unique_together={('case', 'prize')},
        ),
    ]
