# Generated by Django 4.2.24 on 2025-10-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_prize_caseprize_amount_max_usd_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caseprize',
            unique_together=set(),
        ),
    ]
