# Generated by Django 4.2.24 on 2025-09-21 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_client_seed_profile_pf_nonce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Уровень 1'), (2, 'Уровень 2')])),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_bonuses', to='accounts.deposit')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_referral_deposits', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реферальный бонус',
                'verbose_name_plural': 'Реферальные бонусы',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['referrer'], name='referrals_r_referre_d84ab5_idx'), models.Index(fields=['deposit'], name='referrals_r_deposit_a2f37a_idx'), models.Index(fields=['created_at'], name='referrals_r_created_045edb_idx')],
                'unique_together': {('deposit', 'level')},
            },
        ),
    ]
