# Generated by Django 4.2.24 on 2025-09-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(db_index=True, unique=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Процент рефералов (уровень)',
                'verbose_name_plural': 'Проценты рефералов (уровни)',
                'ordering': ('level',),
            },
        ),
    ]
