# Generated by Django 4.2.24 on 2025-09-10 17:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_seed',
            field=models.CharField(blank=True, db_index=True, default=accounts.models._gen_client_seed, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pf_nonce',
            field=models.PositiveIntegerField(default=0, help_text='Счётчик прокруток для текущего client_seed'),
        ),
    ]
