# Generated by Django 4.2.24 on 2025-10-13 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_profile_client_seed_profile_pf_nonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('withdrawal', 'Блокировка вывода'), ('deposit', 'Блокировка ввода'), ('account', 'Блокировка аккаунта')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Причина блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли блокировка')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Блокировка пользователя',
                'verbose_name_plural': 'Блокировки пользователей',
                'ordering': ('-created_at',),
                'unique_together': {('user', 'block_type', 'is_active')},
            },
        ),
    ]
