# Generated by Django 4.2.24 on 2025-10-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userblock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together=set(),
        ),
    ]
