# Generated by Django 4.2.24 on 2025-10-13 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_userblock_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Причина блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли блокировка')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Блокировка аккаунта',
                'verbose_name_plural': 'Блокировки аккаунтов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DepositBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Причина блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли блокировка')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Блокировка ввода',
                'verbose_name_plural': 'Блокировки вводов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WithdrawalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Причина блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли блокировка')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Блокировка вывода',
                'verbose_name_plural': 'Блокировки выводов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='UserBlock',
        ),
    ]
