# Generated by Django 4.2.24 on 2025-09-08 08:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('period_minutes', models.PositiveIntegerField(default=60)),
                ('run_minute', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки кэшбэка',
                'verbose_name_plural': 'Настройки кэшбэка',
            },
        ),
        migrations.CreateModel(
            name='CashbackAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('base_deposits_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('base_withdrawals_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('base_net_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('percent_used', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slot_started_at', models.DateTimeField(db_index=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('calculated', 'Рассчитан'), ('credited', 'Зачислен'), ('cancelled', 'Отменён')], db_index=True, default='calculated', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_accruals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Начисление кэшбэка',
                'verbose_name_plural': 'Начисления кэшбэка',
                'ordering': ('-computed_at', 'id'),
                'unique_together': {('user', 'slot_started_at')},
            },
        ),
    ]
