# Generated by Django 4.2.24 on 2025-09-13 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='completed', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_debits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Списание кэшбэка',
                'verbose_name_plural': 'Списания кэшбэка',
                'ordering': ('-created_at', 'id'),
            },
        ),
    ]
